import type {
  BeasiswaProgram,
  MasterMenu,
  MasterPersyaratan,
  MasterRole,
  PendaftaranRecord,
  UserInternal,
} from "../types";

export const initialPrograms: BeasiswaProgram[] = [
  {
    id: "prog-1",
    kodeBeasiswa: "WEB-DEV-2026",
    namaPelatihan: "Pelatihan Web Developer Specialist",
    deskripsi:
      "Mempelajari pengembangan aplikasi web modern berbasis Fullstack dari tingkat dasar hingga profesional.",
    kuota: 100,
    metode: "Daring (Online)",
    batasPendaftaran: "30 Sept 2026",
    status: "buka",
    isActive: true,
    persyaratanKhusus: [
      "Warga Negara Indonesia (WNI), usia 18 - 35 tahun.",
      "Pendidikan minimal SMA/SMK sederajat (Diutamakan jurusan RPL / Informatika).",
      "Memiliki laptop/komputer pribadi dengan RAM minimal 8GB.",
    ],
    dokumenWajib: [
      "Scan KTP & KK",
      "Scan Ijazah Terakhir",
      "Surat Rekomendasi / Keterangan Bebas Kerja / Kuliah",
    ],
  },
  {
    id: "prog-2",
    kodeBeasiswa: "DATA-2026",
    namaPelatihan: "Pelatihan Data Analyst & SQL",
    deskripsi:
      "Pelajari analisis data, visualisasi, serta pengelolaan database relational untuk kebutuhan industri digital.",
    kuota: 50,
    metode: "Hybrid (Bandung)",
    batasPendaftaran: "15 Okt 2026",
    status: "buka",
    isActive: true,
    persyaratanKhusus: [
      "WNI usia 18 - 32 tahun.",
      "Memiliki pemahaman dasar logika matematika atau statistik.",
      "Bersedia mengikuti sesi tatap muka luring di Bandung.",
    ],
    dokumenWajib: [
      "Scan KTP & KK",
      "Scan Ijazah Terakhir",
      "Surat Keterangan Sehat",
    ],
  },
  {
    id: "prog-3",
    kodeBeasiswa: "UIUX-2026",
    namaPelatihan: "UI/UX Design & Prototyping",
    deskripsi:
      "Menguasai riset pengguna, pembuatan wireframe, hingga rancangan prototipe aplikasi yang efisien.",
    kuota: 75,
    metode: "Daring (Online)",
    batasPendaftaran: "10 Sept 2026",
    status: "segera_tutup",
    isActive: true,
    persyaratanKhusus: [
      "WNI usia 18 - 30 tahun.",
      "Tertarik dalam riset desain produk dan interaksi antarmuka.",
    ],
    dokumenWajib: [
      "Scan KTP & KK",
      "Portofolio Desain / Karya Visual (Opsional)",
      "Ijazah Terakhir",
    ],
  },
];

export const initialPendaftaranList: PendaftaranRecord[] = [
  {
    id: "prm-1",
    kodePermohonan: "REG-2026-090021",
    userId: "user-yosep",
    userName: "Yosep Rohayadi",
    userNik: "3201123456780001",
    beasiswaId: "prog-1",
    beasiswaNama: "Pelatihan Web Developer Specialist",
    beasiswaMetode: "Daring",
    status: "SUBMITTED",
    stepWizardTerakhir: 4,
    submittedAt: "02 Sep 2026",
    tipePengajuan: "Baru Submit",
    biodata: {
      nik: "3201123456780001",
      namaLengkap: "Yosep Rohayadi",
      tempatLahir: "Bandung",
      tglLahir: "1995-08-17",
      jenisKelamin: "L",
      alamat: "Jl. Kebon Sirih No. 12",
      provinsi: "Jawa Barat",
      kabupatenKota: "Kota Bandung",
      kecamatan: "Coblong",
      kelurahan: "Dago",
      noHp: "081234567890",
      email: "yosep@example.com",
    },
    pendidikan: {
      pendidikanTerakhir: "S1 (Sarjana)",
      namaInstansi: "Universitas Komputer Indonesia",
      jurusan: "Teknik Informatika",
      pekerjaanSaatIni: "Software Developer / Freelancer",
    },
    dokumen: [
      {
        persyaratanId: "req-ktp",
        namaPersyaratan: "KTP (Kartu Tanda Penduduk)",
        fileName: "ktp_yosep.jpg",
        fileSize: "1.2 MB",
        mimeType: "image/jpeg",
        format: "JPG",
        isSesuai: true,
      },
      {
        persyaratanId: "req-kk",
        namaPersyaratan: "KK (Kartu Keluarga)",
        fileName: "kk_yosep.pdf",
        fileSize: "1.8 MB",
        mimeType: "application/pdf",
        format: "PDF",
        isSesuai: true,
      },
      {
        persyaratanId: "req-ijazah",
        namaPersyaratan: "Ijazah Terakhir",
        fileName: "ijazah_yosep.pdf",
        fileSize: "1.9 MB",
        mimeType: "application/pdf",
        format: "PDF",
        isSesuai: false,
        catatanRevisi:
          "Scan dokumen buram, mohon di-upload ulang dengan jelas.",
        isRejected: true,
      },
      {
        persyaratanId: "req-rekom",
        namaPersyaratan: "Surat Rekomendasi / Keterangan",
        fileName: "surat_rekomendasi.pdf",
        fileSize: "850 KB",
        mimeType: "application/pdf",
        format: "PDF",
        isSesuai: true,
      },
    ],
  },
  {
    id: "prm-2",
    kodePermohonan: "REG-2026-090022",
    userId: "user-siti",
    userName: "Siti Nurhaliza",
    userNik: "3201987654320002",
    beasiswaId: "prog-2",
    beasiswaNama: "Pelatihan Data Analyst & SQL",
    beasiswaMetode: "Hybrid",
    status: "LULUS_DITERIMA",
    stepWizardTerakhir: 4,
    submittedAt: "01 Sep 2026",
    tipePengajuan: "Hasil Revisi",
    biodata: {
      nik: "3201987654320002",
      namaLengkap: "Siti Nurhaliza",
      tempatLahir: "Jakarta",
      tglLahir: "1998-04-12",
      jenisKelamin: "P",
      alamat: "Jl. Dipati Ukur No. 45",
      provinsi: "Jawa Barat",
      kabupatenKota: "Kota Bandung",
      kecamatan: "Coblong",
      kelurahan: "Lebakgede",
      noHp: "081287654321",
      email: "siti@example.com",
    },
    pendidikan: {
      pendidikanTerakhir: "S1 (Sarjana)",
      namaInstansi: "Institut Teknologi Bandung",
      jurusan: "Sains Data",
      pekerjaanSaatIni: "Junior Analyst",
    },
    dokumen: [],
    verifikasi: {
      verifikatorId: "v-1",
      verifikatorName: "Ahmad Rivaldi",
      statusKeputusan: "disetujui",
      catatanVerifikator: "Seluruh berkas lengkap dan sesuai kualifikasi.",
      verifiedAt: "02 Sep 2026 10:00",
    },
    wawancara: {
      interviewerId: "i-1",
      interviewerName: "Lembaga Seleksi A",
      skorKomunikasi: 85,
      skorTeknis: 86,
      skorKomitmen: 85,
      nilaiWawancara: 85.5,
      statusHasil: "Lulus",
      catatanEvaluasi:
        "Kandidat sangat menguasai analisis data dan antusias.",
      evaluatedAt: "03 Sep 2026 14:30",
    },
  },
  {
    id: "prm-3",
    kodePermohonan: "REG-2026-090023",
    userId: "user-ahmad",
    userName: "Ahmad Hidayat",
    userNik: "3201776543210003",
    beasiswaId: "prog-3",
    beasiswaNama: "UI/UX Design & Prototyping",
    beasiswaMetode: "Daring",
    status: "TIDAK_LULUS_WAWANCARA",
    stepWizardTerakhir: 4,
    submittedAt: "31 Aug 2026",
    tipePengajuan: "Baru Submit",
    biodata: {
      nik: "3201776543210003",
      namaLengkap: "Ahmad Hidayat",
      tempatLahir: "Bogor",
      tglLahir: "1999-11-20",
      jenisKelamin: "L",
      alamat: "Jl. Pajajaran No. 88",
      provinsi: "Jawa Barat",
      kabupatenKota: "Kota Bogor",
      kecamatan: "Bogor Tengah",
      kelurahan: "Tegallega",
      noHp: "081377889900",
      email: "ahmad.h@example.com",
    },
    pendidikan: {
      pendidikanTerakhir: "SMA/SMK Sederajat",
      namaInstansi: "SMKN 1 Bogor",
      jurusan: "Multimedia",
      pekerjaanSaatIni: "Freelance Designer",
    },
    dokumen: [],
    verifikasi: {
      verifikatorId: "v-1",
      verifikatorName: "Ahmad Rivaldi",
      statusKeputusan: "disetujui",
      catatanVerifikator: "Berkas portofolio terlampir.",
    },
    wawancara: {
      interviewerId: "i-1",
      interviewerName: "Lembaga Seleksi A",
      skorKomunikasi: 50,
      skorTeknis: 60,
      skorKomitmen: 55,
      nilaiWawancara: 55.0,
      statusHasil: "Tidak Lulus",
      catatanEvaluasi:
        "Kurang siap mengikuti jadwal penuh kelas harian.",
    },
  },
];

export const initialInternalUsers: UserInternal[] = [
  {
    id: "usr-1",
    name: "Ahmad Rivaldi",
    username: "ahmad@beasiswa.go.id",
    email: "ahmad@beasiswa.go.id",
    role: "verifikator",
    status: "Active",
  },
  {
    id: "usr-2",
    name: "Lembaga Seleksi Eksternal",
    username: "interviewer@beasiswa.go.id",
    email: "interviewer@beasiswa.go.id",
    role: "interviewer",
    status: "Active",
  },
  {
    id: "usr-3",
    name: "Yosep Rohayadi",
    username: "admin@beasiswa.go.id",
    email: "admin@beasiswa.go.id",
    role: "admin",
    status: "Active",
  },
];

export const initialPersyaratan: MasterPersyaratan[] = [
  {
    id: "req-ktp",
    namaPersyaratan: "KTP (Kartu Tanda Penduduk)",
    formatAllowed: "PDF / JPG / PNG",
    maxSize: "2 MB",
    isMandatory: true,
  },
  {
    id: "req-kk",
    namaPersyaratan: "KK (Kartu Keluarga)",
    formatAllowed: "PDF / JPG / PNG",
    maxSize: "2 MB",
    isMandatory: true,
  },
  {
    id: "req-ijazah",
    namaPersyaratan: "Ijazah Terakhir",
    formatAllowed: "PDF / JPG / PNG",
    maxSize: "2 MB",
    isMandatory: true,
  },
  {
    id: "req-rekom",
    namaPersyaratan: "Surat Rekomendasi / Keterangan",
    formatAllowed: "PDF / JPG / PNG",
    maxSize: "2 MB",
    isMandatory: true,
  },
];

export const initialRoles: MasterRole[] = [
  {
    id: "role-verif",
    name: "Verifikator",
    description: "Petugas seleksi administrasi berkas",
    accessibleMenus: ["Verifikasi Seleksi Administrasi"],
  },
  {
    id: "role-int",
    name: "Lembaga Seleksi",
    description: "Tim penguji substantif & wawancara",
    accessibleMenus: ["Proses Wawancara"],
  },
  {
    id: "role-adm",
    name: "Administrator",
    description: "Pengelola master data, sistem & hasil",
    accessibleMenus: [
      "Dashboard",
      "Hasil Seleksi",
      "Data Master",
      "Setting System",
    ],
  },
];

export const initialMenus: MasterMenu[] = [
  {
    id: "menu-1",
    name: "Verifikasi Seleksi Administrasi",
    route: "/verifikator",
    icon: "bi-file-earmark-check",
  },
  {
    id: "menu-2",
    name: "Proses Wawancara",
    route: "/wawancara",
    icon: "bi-chat-square-text",
  },
  {
    id: "menu-3",
    name: "Dashboard & Master",
    route: "/admin",
    icon: "bi-speedometer2",
  },
];
